### ISSUE TITLE
Project name

### ISSUE THREAD

**Issue by machiavel23** [Kornilov1/AI-Dungeon-2-Anons-modded-Versions-Colab#144]
I think we should rename the file to be a bit clearer, I often see others refer to it as "thadunge2's colab" and it confuses retards and sometimes me as well. Here's my idea if you're ok with changing the name:

Open-CYOAI

for Open - Choose Your Own Artificial Intelligence. A reference to OpenAI and the CYOA materials used for training it. What do you think?

**Comment by VBPXKSMI** [comment]
Looking at this, will do ASAP. Not completly sure yet if that will be the name but it could do.
Be aware that as the name changes we will have to change some links in the Colab (the ones that refers to opening it in the first place).

**Comment by machiavel23** [comment]
yep, will keep that in mind. I let this issue open until a final name arrive.

**Comment by VBPXKSMI** [comment]
Another suggested name was "AD/v/ENTURUM".
Don't know if it's better just throwing it in here for further consideration, as well as any other names that may surge.

**Comment by machiavel23** [comment]
it's not bad, but... meh. having the board in it is cool however, we should search around this and the OpenAI and CYOA reference we already use.

**Comment by machiavel23** [comment]
maybe simply

/v/'s Open-CYOAI Project

could be used as a rally banner for the forks of the game. like
Open-CYOAI Enhanced Edition (for thadunge)
Open-CYOAI Clover Edition (for clover)

and so on? I try think in the large scale because someday (((HE))) will trademark (((IT)))

**Comment by VBPXKSMI** [comment]
You can be damn sure he will trademark it, right after people forget it was Open Source in the first place.

Umm that's not a bad idea, but I'm not sure about the /v/ part. You see, I'm thinking that one day (maybe) the entire 4chan community may be on this, so labelling it like that might be counterproductive, even if it's a mainly /v/ project. But this is just my opinion, we should ask in the threads too (and the fork Devs would also need to agree too).

What about "Anons Open-CYOAI Project"?

**Comment by machiavel23** [comment]
> What about "Anons Open-CYOAI Project"?

looks good to me

**Comment by VBPXKSMI** [comment]
Ok, then I will change it soon. Also, will still ask for suggestions in the threads so this shall not be closed for the moment.


By the way, is "Anons Open...", "Anons' Open..." or "Anon's Open..."? 
Can't remember what was the rule in english for these cases when using possesive plural nouns (an to make matters worse "Anons" is an acronym of "Anonymous" in plural, which doesn't have 1 single defined naming convention on what is the correct plural form). 
This is just me trying to be precise, it doesn't matter that much.

**Comment by machiavel23** [comment]
would say anons'

honestly, this rule also always bored me to death

and no matter the name, we need it ASAP. As well as the forks. I'm tired of that small bitch spreading the beta.aidungeon.io link and talking about it as if it was the best thing ever made in life, this shithead is seriously getting on my nerves!!! don't even contribute to any work that need to be done, shits on the colab... what's the point of what we do if in the end everyone just go there because it's easier to play? RRREEEE

**Comment by VBPXKSMI** [comment]
Calm down. He may be a bitch but he has one point correct. 
i.e. we need to differentiate our work from the mormon's one. And that will be possible only when we don't have a single line of his original code in the game.

For now the change of name should suffice, but we would still need to convince the fork devs to do the same and I'm not so sure what do they think about all this (see CloverAnon fork that is MIT licensed) (but maybe that is better than AGPL? He did mention that the mormon can't steal his code even when using it on MIT but I dunno).

**Comment by machiavel23** [comment]
honestly, I'm more worried for thadunge fork name than clover's license. I guess I'll have to take the time to read both. gonna be a pita but i'll be able to settle the question at last. but for thadunge name's, i doubt he can rename his fork, and that could be a problem. I'd prefer to see thadunge and clover work on the same repo, they both have good ideas and options and having them in the same game would be amazing.

**Comment by VBPXKSMI** [comment]
>I'd prefer to see thadunge and clover work on the same repo, they both have good ideas and options and having them in the same game would be amazing.

Me too, but that would depend entirely on them. Ideally we would have both merged, with the option of turning off/on as much settings as possible in game. That way anyone can play the way they desired and the fork devs wouldn't have a reason to bicker over how they want the game to be developed.

**Comment by machiavel23** [comment]
I've read you plan to implement Anons' Open-CYOAI Project. Have you got feedback of the forkanons about it?

**Comment by VBPXKSMI** [comment]
Nothing. Neither thadunge2 (who didn't gave signs of life for 4 days) nor CloverAnon said anything on the matter. But I wouldn't worry to much of them, the name change is mainly for this Colab, if they want to follow it depends on them.

The retards on the threads have neither suggested anything, too worried with the motherfucking bug to do anything of worth. 
If we can't solve it by new year, I'm afraid we should switch back to the v1.0 or at least implement a separated install and play cells like it was suggested in the other issue by "uotalkie", and then develop from there until we can solve the all-in-one cell.

I know, shit sucks, but we can't continue like we are now. An strategic withdrawal may be for the best, for now at least.

**Comment by machiavel23** [comment]
EDIT: link removed

I tell you. that shit IS completely random and out of what anyone can do... except google maybe.

**Comment by VBPXKSMI** [comment]
That cell is cursed, no witchcraft seems to be curing it.

Jokes aside, the fact is that all this issue started after we started using that cell, so we may be forced to roll back if we don't find a solution soon.
I will be putting the Old Colab v1.0 in the OPs from now on, alongside your Beta (not the master branch Colab) so feel free to experiment as much as you want and tell people to give you feedback.

We need to put a time limit until we move on, so lets say 7 days. If we didn't find a solution by then we will need to focus on the Old Colab, either by improving a bit the cells there (without finding another fucking bug) or transplanting as much of the new Colab as we can.

I already transplanted most visual enhancements, but didn't touch any code of the cells, I will leave to you that job (when and if the time comes).

What do you think?

**Comment by machiavel23** [comment]
Well I dropped some tests colabs in the thread, we'll se the results. I fear I'll have to update a bit the code of the v1 before that tho, but we'll see how it works

**Comment by machiavel23** [comment]
yep indeed, had to add 2 pip in the dependencies cell.

**Comment by AtaIanta** [comment]
I'm surprised nobody have proposed Keit-AI yet

**Comment by VBPXKSMI** [comment]
>I'm surprised nobody have proposed Keit-AI yet

Holy shit, you are right, it never occured to me.
As silly as it sounds it could be an option, specially when you consider that "Anons' Open-CYOAI Project" is too long and not that much catchy of a name.

**Comment by machiavel23** [comment]
what's the ref for Keit?

**Comment by AtaIanta** [comment]
A boy falls in love with a girl.
Unable to confess, he is gifted with by a deus ex machina with the girl's phone number. Never minding the strange area code, he immediately calls her, and is overjoyed to find out that she has a crush on him as well.
But, the next day, when he recounts the previous day's confessions to the girl, she only looks at him with a perplexed expression. After some investigation, he finds out that the girl he called is not the same girl he fell in love with. In fact, she doesn't exist in this universe at all. She is the girl's alternate universe counterpart, who has fallen in love with the MC's own AU self, who too is blissfully unaware of her crush.
Hijinks ensue as the two strike up a deal to give each other their darkest, most private secrets in order to equip the other with the weapons they need to conquer the heart of their other selves. While the two chase their respective loved ones, DRAMA ensues as they begin to fall in love with each other instead and question the NATURE of LOVE.

**Comment by AtaIanta** [comment]
reference to /a/'s pasta

**Comment by VBPXKSMI** [comment]
Good pasta. Feel free to suggest any other names, especially if they are 4chan related.

**Comment by machiavel23** [comment]
Ah ok. I don't browse /a/, didn't knew about that.

**Comment by machiavel23** [comment]
Would be great if the forkanons would confirm or deny the will to globalize the project

**Comment by VBPXKSMI** [comment]
Would be great yeah. Everything could be on a single repository too I think.
Though, the licenses and naming issues might need to be sorted out first. (maybe).

**Comment by DonaldTsang** [comment]
Maybe "oubliette"?

**Comment by DonaldTsang** [comment]
@machiavel23 @VBPXKSMI licensing might be an issue since AIDUngeon might be going closed source or even SaSS.
