### ISSUE TITLE
Disclaimer modifications

### ISSUE THREAD

**Issue by machiavel23** [Kornilov1/AI-Dungeon-2-Anons-modded-Versions-Colab#145]
I'd like you to check the latest modifications i made to the Disclaimer area in the beta branch and tell me if it's ok with you or not. We will need to do a bit of research to complete it before merging, evidences are needed to replace all the BETA TEXT stuff

**Comment by VBPXKSMI** [comment]
Will add most in the disclaimer. For the things that still need more checking, I won't, but kept the "Beta text" parts in the beta branch for when we find it.

**Comment by machiavel23** [comment]
perfect. I'm closing then.
