### ISSUE TITLE
Question about the disclaimer

### ISSUE THREAD

**Issue by machiavel23** [Kornilov1/AI-Dungeon-2-Anons-modded-Versions-Colab#153]
I'm considering putting the disclaimer at the very bottom of the page. It's actually quite a wall of text before the actual useful cells and I feel like it's not really necessary to keep it so high. What do you think @Kornilov1 ? At least until we manage to fill the blanks (aka BETA TEXT)

**Comment by VBPXKSMI** [comment]
I agree, is quite big with all those "Beta text" in the way. 
Do it, but if there is a way (any way) of collapsing the cells upon first opening the Colab it wouldn't be necessary at all and would be the best solution (I know you once said that was impossible, but confirm that to me nonetheless).

**Comment by machiavel23** [comment]
well there might be a way if we provide a css in the "Colab Notebooks" folder I guess. Apparently, jupyter notebooks (tha basis of colab notebooks) can use a bunch of meta parameters and extensions, so there might be a way, but it's quite a hassle to check it until wee manage to solve or bypass the disconnection issue. maybe a manual edit in the .ipynb code itself could do the trick meanwhile though

**Comment by VBPXKSMI** [comment]
Yes, we should check that extension possibilty. Hopefully the last fix works.
Although I'm reluctant to put it at the end of the Colab since it would look weird and out of place (I think that the definitive place should be up there with all the info, and the code cells all should come last).

**Comment by machiavel23** [comment]
I agree too, but until we manage to find a way to make it less "wally", I guess it's better.

Markdown (the text cells) can build tables using pipes. I've checked and it doesn't look too bad, despite being a bit small for my tast. I'll try a cell with the disclaimer like that and show it to you when ready, might be another option, and simpler option too.

also one last thing. once we're sure the fix is good and once we've settled something about the disclaimer, we should make an official release in the release tab of github. it'll probably be better than putting multiple links with different urls everyday in the thread. It'll be THE link until next release, see? like that, we can improve the code without fucking up everyone's play

**Comment by VBPXKSMI** [comment]
Very well, I leave the disclaimer thing to you.
About the second point, yeah might be better (will have to fuck around with it for a while cause I'm new to GitHub myself and I'm still trying to understand how it works).

**Comment by machiavel23** [comment]
ok then. i'll try a few things for the disclaimer and show them to you then

**Comment by machiavel23** [comment]
since the table seems to have settled this, I close the issue
