### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by Muskelmagier** [Kornilov1/AI-Dungeon-2-Anons-modded-Versions-Colab#161]
I have no idea about Programming but i get this error everytime.
I already tried to reinstall AIdungeon.

i am using the Open CYOAI Colab v1.22.ipynb 

Traceback (most recent call last):
  File "play.py", line 9, in <module>
    from story.story_manager import *
  File "/content/gdrive/My Drive/AIDungeon/story/story_manager.py", line 191
    try:
      ^
SyntaxError: invalid syntax

**Comment by machiavel23** [comment]
yeah, apparently they forgot a ) in a line. it's answered in the thread already, and I saw a pull request or something. will be fixed soon, probably, but it's not a colab glitch, so I'm closing
