### ISSUE TITLE
Gdrive deletion cell has no confirmation.

### ISSUE THREAD

**Issue by lordpidey** [Kornilov1/AI-Dungeon-2-Anons-modded-Versions-Colab#162]
So....

Long story short, I clicked the wrong cell, and wiped my entire Gdrive.

I didn't lose anything because I had it all backed up elsewhere.

I understand the need for a gdrive wipe cell, but could we add a confirmation to it?  Perhaps add a step where the user has to type "delete my entire gdrive", just so we are sure the user is doing what they want.

**Comment by machiavel23** [comment]
Sure, it can easily be implemented. I also think asking for a confirmation is a necessity, it's quite raw for now. It'll be done with the rework of the colab, so I let the issue open until then.

**Comment by machiavel23** [comment]
just implemented, now live on the beta branch

https://colab.research.google.com/github/Kornilov1/AI-Dungeon-2-Anons-modded-Versions-Colab/blob/beta/Open_CYOAI_BETA.ipynb
