### ISSUE TITLE
Reorganized beta

### ISSUE THREAD

**Issue by machiavel23** [Kornilov1/AI-Dungeon-2-Anons-modded-Versions-Colab#163]
@Kornilov1 

As you can see, I've reorganized the beta. The actual concept solves a problem.

The problem of git pull and git merge is that the whole file gets replaced with each merge, meaning we have to make sure all versions are updated before merging. let's say, you worked on a new cell on the master branch, and i updated the main cell on the beta branch.

before the beta can be merge to master, the beta will have to add your new cell, or it will be overwritten by the beta ipynb.

The new layout of the beta allows both of us to work independtly on the cells in beta branch, (with the dev-xxx files) and once the work is done, simply copy-paste the code to the main ipynb (Open CYOAI BETA). Afterwards, when the main ipynb is tested, we can easily merge it to the master branch.

This layout is the best imo to ensure a good workflow between us, and with any fork that could popup.

Once we have our first release done, we'll be able to share only the release link, and use the master branch as the main dev branch, like it is supposed to be, to get rid of the beta branch, but with keeping the same layout. that way, we will be able to work on the master branch independently, on each cell independently, without fucking up the public link. and once our work is done on the master branch, just re-release it.

seems like a good way to avoid the hassle to have multiple ipynb (master and beta), and each paste on the main dev ipynb will show up as a commit, so everything should be good and easily traceable.

**Comment by VBPXKSMI** [comment]
Good idea. 
Maybe we could also create a "Test.ipynb" file where anyone could test the whole Colab code, to see how it looks as a whole, and to be able to test it before merging it in the main file.

Also, we should include a warning that says something along the lines of 

>Before commiting your changes:
Copy all the code you have currently on display (Ctrl + A then Ctrl + C)
Then go back to the repo page and press F5
If you don't see any (very) recent commit to the file you intended to change, you are free to commit your changes
Just open that file again, erase all the code, and paste (Ctrl + V) your copied code from before and commit changes"

This way we would prevent 2 or more people from working on the same file at the same time, and fucking up the commits.

**Comment by machiavel23** [comment]
the whole point of this system is to actually use the main file as a test file, since it'll be in that one that we will paste the code. beside, each cell will be quite tested before being pasted on the big one. check this:

before the first release

on beta branch : dev-files pasted to open cyoai beta ipynb pushed on master branch
(op main link is master branch, op dev link is beta)

for the release

master branch building release
(now the only main link in op is release link. we can now work directly on master branch and delete beta branch, so the op dev link is master branch)

after the release

on master branch :  dev-files pasted to open cyoai.ipynb

when new open cyoai.ipynb is ready, we simply re-release it

we can't fuckup with that. and if anybody want to edit the files, they have to fork them and submit pull request. as long as you and i are the only ones able to validate and merge the pulls, the randoms can't fuckup the files. and as long as the main link is the one leading to the release, even if we fuck up the file, it'll be the dev file, not the released one everyone use. I might not explain it correctly due to my poor english but trust me, it's pretty fuckproof. we just have to tag our commits with a starting obvious word like WIP, OK, TEST... and we'll be good

**Comment by VBPXKSMI** [comment]
>as long as you and i are the only ones able to validate and merge the pulls, the randoms can't fuckup the files

Fair point actually.
>I might not explain it correctly due to my poor english but trust me, it's pretty fuckproof. we just have to tag our commits with a starting obvious word like WIP, OK, TEST... and we'll be good

Well, as usual I'm just being overly-cautious, you know that things never go like they are supposed to. 
For now lets roll with your idea, and if anything arises we will deal with it and adapt.

**Comment by machiavel23** [comment]
sure thing. I'll add a quick tag definitions for thecommits in the roadmap

**Comment by machiavel23** [comment]
not really an issue and the system seems to work, so I close this
