### ISSUE TITLE
Updating versions

### ISSUE THREAD

**Issue by Muskelmagier** [Kornilov1/AI-Dungeon-2-Anons-modded-Versions-Colab#164]
Hi, it would be nice if it would be possible to forcefully update my own version of AIdungeon even if I have made a change to my Data. 

It is every time a great hassle ,if I made a small insignificant change or fix and afterward I have to reinstall AI dungeon if I want to update.

Maby if the Colab detects that my version is changed ask a second time to update?

**Comment by VBPXKSMI** [comment]
@Muskelmagier Are you using the Colab v1.0 per chance? (That Colab is not getting updates at the moment)
Because I'm pretty sure the Colab Beta already has what you are looking for, unless I'm not understanding what you are asking for.

**Comment by machiavel23** [comment]
yes, the beta colab automatically checks for github update before launching play.py. It does a `git fetch -v` and show you the results, then ask you if you need/want to update. you can answer yes or no depending on what you want. no will go straight to play.py, while yes will run a `git pull` then go to play.py.

**Comment by Muskelmagier** [comment]
I am using the most recent version of the colab.
But the problem for me is if I change something from the data of Ai dungeon, the colab no longer is able to update if a new version of the Thadunge2 fork is released

**Comment by machiavel23** [comment]
hmm... I'll check that soon. I need to finish inspecting issues on all git hub and I'l take a look

**Comment by machiavel23** [comment]
Many changes have been done in the way github behaves in colab. can you try the beta and tell if it's still an issue?

**Comment by machiavel23** [comment]
should be fixed with #170

**Comment by machiavel23** [comment]
@Muskelmagier still an issue?

**Comment by Muskelmagier** [comment]
As fas as i can see no longer an issue.

**Comment by machiavel23** [comment]
thanks
