### ISSUE TITLE
[W-Change] Colab Troubleshooting

### ISSUE THREAD

**Issue by machiavel23** [Kornilov1/AI-Dungeon-2-Anons-modded-Versions-Colab#167]
(Issue pasted from the other repo, opened by @SaberWonderland )
> 
> 
> **Link of concerned page:**
> https://github.com/OpenCYOAI/OpenCYOAI/wiki/Colab-Troubleshooting
> 
> **What to find:**
> Step 6 block
> 
> **What to put:**
> Please Change this: The absolute best thing you can do is fill out the form at the bottom of the pastebin and post it in the thread. The more information the devs have the faster they can figure out what is causing the constant disconnecting and fix it.
> 
> To this:
> The absolute best thing you can do is fill out the form at the bottom of the pastebin and post it in the thread. While there is no known fix any and all information helps.
> 
> Please change: In the meantime while they fix it currently the 1.0 version has been completely stable for me and hasn't disconnected once. If you have all the files already downloaded in your google drive you can just follow these steps and start playing right now
> 
> To this: There is no fix known currently for this bug. The devs believe it's on Google's side completely and there is nothing we can do about it. It shouldn't actually make a difference but 1.0 is stable for some people. If you have all the files already downloaded in your google drive you can just switch to the 1.0 branch by following these steps:
> 
> Of course leave in the instruction steps. Sorry I haven't updated it in a few days the new bugs that showed up kept getting fixed so I felt like there was no point in updating but I might as well try to quell the ignorance of the disconnect bug being on our end rather than Google's.

Answer of @OpenCYOAI
> 
> 
> yeaah.... if i put that myself those retards will create another drama for nothing. I'll let korn handle this when he'll finally accept the repo ownership. but thanks for the submission, it'll probably be changed

**Comment by SaberWonderland** [comment]
Gonna go ahead and close this as I just edited the troubleshooting page myself.
