### ISSUE TITLE
[W-PROMPT]

### ISSUE THREAD

**Issue by SaberWonderland** [Kornilov1/AI-Dungeon-2-Anons-modded-Versions-Colab#171]
**Title:**
Battle Angel Iris

**Tags:**
*Futanari *Rape *Mind Control *Corruption *Magical Girl

**Context:**
You are Iris, a battle angel. The battle angels are an order of maidens who battle evil with their sacred powers. You have spent your entire career fighting to put a stop to the world domination of the extra terrestrial invaders known as reizphobia. The leader of reizphobia who is known as Dark Empress Rexos has captured you. Tentacles have taken hold of your body and you are naked and cannot move.

**Prompt:**
Dark Empress Rexos approaches you and reveals her massive 16 inch dick and orders you to begin sucking it. You find yourself unable to resist and begin sucking her dick against your will.

**Comment by machiavel23** [comment]
@MunasheDov don't forget to click "close the issue once you've done it
