### ISSUE TITLE
[DEV] Can't embed wiki in colab

### ISSUE THREAD

**Issue by machiavel23** [Kornilov1/AI-Dungeon-2-Anons-modded-Versions-Colab#176]
So, because of github security strategies, it seems impossible to embed the wiki in a <iframe> or <embed> tag inside colab. After quite some researches, the only way I found to bypass that is a bit complicated. Basically, convert the wiki to a jekyll mini-site hosted directly by github. It can easily be done in the settings, but have some flaws:

The wiki cannot be the direct source, so we would have to create a directory in the repo containing all the wiki md files and use this directory as the source. It will require to edit the links to point at pages instead of urls, and a few more edits (like the tables), and Home.md must be renamed README.md. Also, any change made in the wiki will require to be pasted to the folder page as well. We could also just remove the wiki and use this to avoid duplicate, since it will also support html (tags and files) much better.

I prepared a test repo here: https://github.com/machiavel23/test/
you can see the result here (not edited, the links will redirect to actual wiki): https://machiavel23.github.io/test/
it uses Dinky theme, but others can be viewed here: https://github.com/pages-themes

So the question is do we set a mini jekyll site to be able to embed it in a "wiki" tab on colab, or it's not worth the hassle?

@VBPXKSMI 

EDIT you can check the bug here https://colab.research.google.com/github/VBPXKSMI/Open-CYOAI-Project/blob/beta/dev_v3.ipynb#scrollTo=65FBEgvGPN7U (wiki tab) the first iframe points to the jekyll mini site, and the second directly to the wiki url

**Comment by VBPXKSMI** [comment]
@machiavel23 Actually, I had already  looked into using jekyll before (when I was first creating the Wiki), but at the time it didn't see like it was worth the hassle.
I'm not sure, it could be an improvement but it can also become more difficult to use for the Wiki collaborators, not to mention the re-write that would imply.

Also the iframe bug needs checking yes, if the output could be centered and scaled somehow it could work on Colab.

Overall, I think using jekyll **alone** might be worth looking into (although I'm still not sure). But the implementation of it in Colab tabs would require a bit more work for it to look decent, otherwise  a direct link to the WIki would be better.

Maybe ran some tests on your side, but focus on the issue later? At least until I'm somewhat done with the re-formatting I'm doing.

**Comment by machiavel23** [comment]
don't worry for the iframe formatting, it's pretty easy. the main concern is **do we want it in colab or not**? If not, I'll have to add quite some text and links as small helpers through more or less everything because retards, but if yes, then the iframe will be there so no bloating in other stuff, that's it for the basics.

Another thing on using jekyll. We should be able to do html pages in it, so we can do one with a jupyter wrapper like Voilà to make the colab look more like a web-app. So if we decide to use jekyll, the best way to do it would be to create a repo dedicated to it, that would allow us to manage the pages and the theme more conveniently than just use a pre-made theme that doesn't correctly fit what we want. But someone with good html/css skill would be good to find to take care of it, because I won't be able to work on the colab AND the jekyll same time.

so, to make it short. with jekyll, we can have cute iframe in colab to show the wiki and maybe even make the colab look like a web-app. without jekyll, there will be some help bloat in each of the colab output tabs, and not much more custom design as it is now.

**Comment by VBPXKSMI** [comment]
>do we want it in colab or not?

That's the issue isn't it? I'm not sure, I would wait for the next version of Colab to be finished to see how everything looks, implementing the Wiki after shouldn't take that much time.

>But someone with good html/css skill would be good to find to take care of it

And this is another issue entirely, either some of us takes care of it aside from maintening the Wiki, or we seek another Anon for help.
